Refactor/repo&command
teaconmc/SimplePermission pull request #2
Opened 2021-01-17 05:12 UTC by SeraphJACK

2021-01-17 05:20 UTC, SeraphJACK commented
TODOs:

- [ ] Implement command to change gamemode
- [ ] Trigger auto saving
- [ ] Implement "verbose mode" - to monitor permission details

2021-01-17 06:49 UTC, 3TUSK requested changes
+700 -367 reeeeeeeeeeeeeeee

2021-01-17 06:49 UTC, 3TUSK commented on src/main/java/org/teacon/permission/command/arguments/ArgumentsRegistry.java
> +public final class ArgumentsRegistry {
直接写进主类里？

2021-01-17 06:49 UTC, 3TUSK commented on src/main/java/org/teacon/permission/command/arguments/ParentInput.java
> +public class ParentInput {
这个类看上去只是对 `String parentName` 的一层包装，能否扁平化（即 `ParentArgumentType implements ArgumentType<String>`）？

2021-01-17 06:49 UTC, 3TUSK commented on src/main/java/org/teacon/permission/command/arguments/UserGroupInput.java
> +public class UserGroupInput {
同 `ParentInput`。

2021-01-17 06:49 UTC, 3TUSK commented on src/main/java/org/teacon/permission/repo/UserDataRepo.java
> +        PLAYER_DATA = configRoot.resolve("player_data.dat");
成员字段全大写……

2021-01-17 06:49 UTC, 3TUSK commented on src/main/java/org/teacon/permission/repo/UserDataRepo.java
> +        Files.write(PLAYER_DATA, GSON.toJson(this.users).getBytes(StandardCharsets.UTF_8), StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
没有 `StandardOpenOptions.WRITE` 真的能写？

2021-01-17 06:49 UTC, 3TUSK commented on src/main/java/org/teacon/permission/command/SimplePermissionCommand.java
> +                .then(Commands.literal("createGroup")
@ustc-zzzz 我需要一点思路，你们命令圈子怎么看驼峰？还是说应该用下划线？

2021-01-17 09:41 UTC, SeraphJACK commented on src/main/java/org/teacon/permission/command/arguments/ArgumentsRegistry.java
> +public final class ArgumentsRegistry {
那样感觉会很乱（

命令相关的注册放到一起，免得后面忘了比较好

2021-01-17 09:42 UTC, SeraphJACK commented on src/main/java/org/teacon/permission/command/arguments/ParentInput.java
> +public class ParentInput {
原版都是封装成了 Input ，我这里模式保持和原版一致

2021-01-17 09:43 UTC, SeraphJACK commented on src/main/java/org/teacon/permission/repo/UserDataRepo.java
> +        Files.write(PLAYER_DATA, GSON.toJson(this.users).getBytes(StandardCharsets.UTF_8), StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
我测试没问题？

2021-01-17 09:43 UTC, SeraphJACK commented on src/main/java/org/teacon/permission/command/arguments/UserGroupInput.java
> +public class UserGroupInput {
同上

2021-01-17 11:15 UTC, ustc-zzzz commented on src/main/java/org/teacon/permission/command/SimplePermissionCommand.java
> +                .then(Commands.literal("createGroup")
@3TUSK  一般不会出现两个连着的单词，通常是 `group create` 什么的

2021-01-17 11:20 UTC, SeraphJACK commented on src/main/java/org/teacon/permission/command/SimplePermissionCommand.java
> +                .then(Commands.literal("createGroup")
group create 的话万一有一个叫做 create 的 group 怎么办呢（

2021-01-17 13:12 UTC, ustc-zzzz commented on src/main/java/org/teacon/permission/command/SimplePermissionCommand.java
> +                .then(Commands.literal("createGroup")
@SeraphJACK `group create <name>`，然后把上面那堆都改成 `group xxx <name> <xxx>` 之类的

2021-01-17 13:33 UTC, SeraphJACK commented on src/main/java/org/teacon/permission/command/SimplePermissionCommand.java
> +                .then(Commands.literal("createGroup")
@ustc-zzzz 那也太蠢了。这个命令的风格我是模仿了 luckperms 的，它的 create group 就是 `/lp creategroup <name>`

2021-01-18 10:34 UTC, SeraphJACK commented on src/main/java/org/teacon/permission/command/SimplePermissionCommand.java
> +                .then(Commands.literal("createGroup")
我已经把所有驼峰的都改成全小写了

2021-01-18 10:35 UTC, SeraphJACK commented
merge 之后还得把 forge 升个版本，然后上 `RegisterCommandsEvent` （

2021-01-18 11:46 UTC, SeraphJACK commented
The suggestion provider is somehow broken and I don't really know how to implement properly, help wanted.

2021-01-18 11:48 UTC, SeraphJACK commented
Basically the situation is:

- To give the suggestions I need to get a preivous argument (for example, list all parents of the user group given before)
- When `listSuggestions` is called, the arguments are not parsed
- Not able to give suggestions

2021-01-18 11:48 UTC, SeraphJACK commented
Argument types encountering this issue:

- `ParentArgumentType`
- `PermissionNodeArgumentType`

2021-01-18 18:14 UTC, 3TUSK requested changes
> merge 之后还得把 forge 升个版本，然后上 `RegisterCommandsEvent`

那大可以现在就加上，记得在 `mods.toml` 里声明版本要求

2021-01-19 00:37 UTC, SeraphJACK commented on src/main/java/org/teacon/permission/command/SimplePermissionCommand.java
> +                .then(Commands.literal("createGroup")
@3TUSK 你怎么看

2021-01-19 00:44 UTC, 3TUSK requested changes
刚才意外发现本地还有点东西……

2021-01-19 00:44 UTC, 3TUSK commented on src/main/java/org/teacon/permission/repo/UserGroup.java
>      public String prefix = "";
https://github.com/teaconmc/SimplePermission/commit/a1903f3da9ba136732aa3ef18faa381f57cbc1bd
手动 cherry-pick 一下

2021-01-19 00:51 UTC, SeraphJACK commented on src/main/java/org/teacon/permission/repo/UserGroup.java
>      public String prefix = "";
CONFLICT

2021-01-19 00:56 UTC, SeraphJACK commented on src/main/java/org/teacon/permission/repo/UserGroup.java
>      public String prefix = "";
cherry pick 完了，还多了个 todo

2021-01-19 06:57 UTC, SeraphJACK commented
怎么 Actions 还爆炸了

2021-01-20 11:56 UTC, ustc-zzzz commented on src/main/java/org/teacon/permission/repo/UserDataRepo.java
> +        Files.write(PLAYER_DATA, GSON.toJson(this.users).getBytes(StandardCharsets.UTF_8), StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
没有问题的，如果你看 JavaDocs 就知道，`Files.write` 是默认把 `StandardOpenOptions.WRITE` 加上的。

2021-01-24 07:20 UTC, SeraphJACK commented
能 merge 了吗.jpg

2021-01-24 08:27 UTC, 3TUSK approved these changes
我暂时想不到哪里还有问题了……

2021-01-24 08:27 UTC, merged